name: Build Android APK & AAB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Télécharge le code
    - name: Checkout code
      uses: actions/checkout@v3
      
    # 2. Installe Java
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    # 3. Rendre gradlew exécutable
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    # 4. Build APK Debug
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    # 5. Build APK Release
    - name: Build Release APK
      run: ./gradlew assembleRelease
      
    # 6. Build AAB (Android App Bundle)
    - name: Build AAB
      run: ./gradlew bundleRelease
      
    # 7. Upload APK Debug
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
        
    # 8. Upload APK Release  
    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk
        retention-days: 7
        
    # 9. Upload AAB
    - name: Upload AAB
      uses: actions/upload-artifact@v3
      with:
        name: app-release-aab
        path: app/build/outputs/bundle/release/app-release.aab
        retention-days: 7
